#!/bin/sh

set -e 

SSH_CFG=`mktemp`

echo "destroying the current environment and bootstrapping a new one"
echo

sleep 5
# remove existing builds
vagrant box remove -f /tmp/builds/111amd-jokerng-jailhost.box || true
vagrant box remove -f /tmp/builds/111amd-jokerng-library.box || true

vagrant destroy -f  jailhost || true
vagrant destroy -f  library || true

( cd packer && ./build_jokerng-jailhost )
( cd packer && ./build_jokerng-library )

vagrant up

vagrant ssh-config > $SSH_CFG

echo "Geerating basejail and jail packages before uploading them to the library"
echo
echo

sleep 5

ssh -F $SSH_CFG jailhost sudo '/root/bin/basejail2pkg "11.1-RELEASE-p9"'
echo "creating template jail"
ssh -F $SSH_CFG jailhost sudo 'ezjail-admin create -b template-42 "172.31.0.201" > /dev/null'
echo "creating the application jails based on the template"
ssh -F $SSH_CFG jailhost sudo '/root/bin/jail2pkg template-42 myapp-1.0 "172.31.0.201"'
ssh -F $SSH_CFG jailhost sudo '/root/bin/jail2pkg template-42 myapp-1.1 "172.31.0.201"'
ssh -F $SSH_CFG jailhost sudo '/root/bin/jail2pkg template-42 myapp-1.2 "172.31.0.201"'

echo "uploading the application jails to the library"
scp -F $SSH_CFG -3 jailhost:*txz library:
ssh -F $SSH_CFG library sudo 'mv *txz /var/library'
ssh -F $SSH_CFG library sudo 'pkg repo /var/library'

echo "installing the application jails by using pkg install"
ssh -F $SSH_CFG jailhost sudo 'pkg update -r library'
ssh -F $SSH_CFG jailhost sudo 'pkg search -r library jail'
ssh -F $SSH_CFG jailhost sudo 'pkg install -y jokerng-jail-myapp-1.0-0.1_1 jokerng-jail-myapp-1.1-0.1_1 jokerng-jail-myapp-1.2-0.1_1'
ssh -F $SSH_CFG jailhost sudo 'ezjail-admin startcrypto && ezjail-admin list && zfs list| grep jails'
sleep 10
echo
echo
echo "removing the application jails"
echo
echo
ssh -F $SSH_CFG jailhost sudo 'ezjail-admin stopcrypto'
ssh -F $SSH_CFG jailhost sudo 'pkg delete -y jokerng-jail-myapp-1.0-0.1_1 jokerng-jail-myapp-1.1-0.1_1 jokerng-jail-myapp-1.2-0.1_1'
ssh -F $SSH_CFG jailhost sudo 'zfs list | grep jails'

rm -rf $SSH_CFG
